name: Build and Deploy Static Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build and optimize
      run: |
        bun run build
        
    - name: Generate build info
      run: |
        echo "Build completed at $(date)" > dist/build-info.txt
        echo "Git commit: ${{ github.sha }}" >> dist/build-info.txt
        du -sh dist/ >> dist/build-info.txt
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: optimized-portfolio
        path: dist/
        retention-days: 30