name: Build Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Build and optimize
      run: |
        bun run build
        
    - name: Generate build info
      run: |
        echo "Build completed at $(date)" > out/build-info.txt
        echo "Git commit: ${{ github.sha }}" >> out/build-info.txt
        du -sh out/ >> out/build-info.txt
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: optimized-portfolio
        path: out/
        retention-days: 30